spring:
  config:
    activate:
      on-profile: dev   # dev 프로필일 때만 활성화

springdoc:
  swagger-ui:
    enabled: true       # 로컬/개발 환경에서는 Swagger 열기
  api-docs:
    enabled: true

# 로깅 설정
logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8080